name: Test and Release

on:
  push:
    branches:
      - "master"
    tags:
      # normal versions
      - "v[0-9]+.[0-9]+.[0-9]+"
      # pre-releases
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-libgpiod:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    outputs:
      libgpiod_path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v6
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf automake libtool pkg-config autoconf-archive
      - name: Build libgpiod 2.x
        run: |
          wget https://mirrors.edge.kernel.org/pub/software/libs/libgpiod/libgpiod-2.2.1.tar.xz
          tar -xvf libgpiod-2.2.1.tar.xz
          cd libgpiod-2.2.1
          CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --prefix=/usr/local --enable-tools --enable-bindings-cxx
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Upload libgpiod artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: libgpiod-2.2.x
          path: |
            /usr/local/bin/gpiodetect
            /usr/local/include/gpiod.h
            /usr/local/include/gpiod.hpp
            /usr/local/include/gpiodcxx
            /usr/local/include/gpiod/*.h
            /usr/local/lib/libgpiod*.so*
            /usr/local/lib/libgpiod*.a
            /usr/local/lib/libgpiodcxx*.so*
            /usr/local/lib/libgpiodcxx*.a

  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    needs: build-libgpiod
    steps:
      - uses: actions/checkout@v6
      - name: Download libgpiod
        uses: actions/download-artifact@v6
        with:
          name: libgpiod-2.2.x
          path: libgpiod
      - name: Install libgpiod into system
        run: |
          sudo cp libgpiod/bin/gpiodetect /usr/local/bin/
          sudo cp -r libgpiod/include/* /usr/local/include/
          sudo cp -r libgpiod/lib/* /usr/local/lib/

          sudo ldconfig
      - uses: ioBroker/testing-action-check@v1
        with:
          node-version: '20.x'
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'
          lint: true

  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ${{ matrix.os }}
    needs: build-libgpiod
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Download libgpiod
        uses: actions/download-artifact@v6
        with:
          name: libgpiod-2.2.x
          path: libgpiod
      - name: Install libgpiod into system
        run: |
          sudo cp libgpiod/bin/gpiodetect /usr/local/bin/
          sudo cp -r libgpiod/include/* /usr/local/include/
          sudo cp -r libgpiod/lib/* /usr/local/lib/

          sudo ldconfig
      - uses: ioBroker/testing-action-adapter@v1
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'


  # Deploys the final package to NPM
  deploy:
    needs: [check-and-lint, adapter-tests]

    # Trigger this step only when a commit on any branch is tagged with a version number
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    # Write permissions are required to create Github releases
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - name: Download libgpiod
        uses: actions/download-artifact@v6
        with:
          name: libgpiod-2.2.x
          path: libgpiod
      - name: Install libgpiod into system
        run: |
          sudo cp libgpiod/bin/gpiodetect /usr/local/bin/
          sudo cp -r libgpiod/include/* /usr/local/include/
          sudo cp -r libgpiod/lib/* /usr/local/lib/

          sudo ldconfig
      - uses: ioBroker/testing-action-deploy@v1
        with:
          node-version: '20.x'
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'
          github-token: ${{ secrets.GITHUB_TOKEN }}

#          # When using Sentry for error reporting, Sentry can be informed about new releases
#          # To enable create a API-Token in Sentry (User settings, API keys)
#          # Enter this token as a GitHub secret (with name SENTRY_AUTH_TOKEN) in the repository options
#          # Then uncomment and customize the following block:
#          sentry: true
#          sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          sentry-project: "iobroker-rpi2"
#          sentry-version-prefix: "iobroker.rpi2"
#          # If your sentry project is linked to a GitHub repository, you can enable the following option
#          # sentry-github-integration: true
