name: Test and Release

on:
  push:
    branches:
      - "master"
    tags:
      # normal versions
      - "v[0-9]+.[0-9]+.[0-9]+"
      # pre-releases
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-libgpiod:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    outputs:
      libgpiod_path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          wget http://ftp.de.debian.org/debian/pool/main/libg/libgpiod/libgpiod-dev_2.2.1-2+deb13u1_amd64.deb -O /tmp/libgpiod-dev.deb
          mkdir -p /tmp/libgpiod
          dpkg-deb -x /tmp/libgpiod-dev.deb /tmp/libgpiod
      - name: Upload libgpiod artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: libgpiod-2.2.x-minimal
          path: |
            /tmp/libgpiod/usr/include/gpiod.h
            /tmp/libgpiod/usr/include/gpiod.hpp
            /tmp/libgpiod/usr/include/gpiodcxx
            /tmp/libgpiod/usr/lib/x86_64-linux-gnu/libgpiod*.so*
            /tmp/libgpiod/usr/lib/x86_64-linux-gnu/libgpiod*.a

  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    needs: build-libgpiod
    steps:
      - uses: actions/checkout@v3
      - name: Download libgpiod
        uses: actions/download-artifact@v4
        with:
          name: libgpiod-2.2.x-minimal
          path: libgpiod
      - name: Install libgpiod into system
        run: |
          sudo cp -r libgpiod/include/* /usr/local/include/
          sudo cp -r libgpiod/lib/* /usr/local/lib/

          sudo ldconfig /usr/local/lib/x86_64-linux-gnu
      - uses: ioBroker/testing-action-check@v1
        with:
          node-version: '20.x'
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'
          lint: true

  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ${{ matrix.os }}
    needs: build-libgpiod
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Download libgpiod
        uses: actions/download-artifact@v4
        with:
          name: libgpiod-2.2.x-minimal
          path: libgpiod
      - name: Install libgpiod into system
        run: |
          sudo cp -r libgpiod/include/* /usr/local/include/
          sudo cp -r libgpiod/lib/* /usr/local/lib/

          sudo ldconfig /usr/local/lib/x86_64-linux-gnu
      - uses: ioBroker/testing-action-adapter@v1
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'


  # Deploys the final package to NPM
  deploy:
    needs: [check-and-lint, adapter-tests]

    # Trigger this step only when a commit on any branch is tagged with a version number
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    # Write permissions are required to create Github releases
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Download libgpiod
        uses: actions/download-artifact@v4
        with:
          name: libgpiod-2.2.x-minimal
          path: libgpiod
      - name: Install libgpiod into system
        run: |
          sudo cp -r libgpiod/include/* /usr/local/include/
          sudo cp -r libgpiod/lib/* /usr/local/lib/

          sudo ldconfig /usr/local/lib/x86_64-linux-gnu
      - uses: ioBroker/testing-action-deploy@v1
        with:
          node-version: '20.x'
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'
          github-token: ${{ secrets.GITHUB_TOKEN }}

#          # When using Sentry for error reporting, Sentry can be informed about new releases
#          # To enable create a API-Token in Sentry (User settings, API keys)
#          # Enter this token as a GitHub secret (with name SENTRY_AUTH_TOKEN) in the repository options
#          # Then uncomment and customize the following block:
#          sentry: true
#          sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          sentry-project: "iobroker-rpi2"
#          sentry-version-prefix: "iobroker.rpi2"
#          # If your sentry project is linked to a GitHub repository, you can enable the following option
#          # sentry-github-integration: true
